### ISSUE TITLE
 Drawbacks with gitignore since it doesn't exclude the venv folder

### ISSUE THREAD

**Issue by cgaray22** [encisosystems/carpa#90]
Drawbacks with gitignore since it doesn't exclude the venv folder, .venv / venv venv / * is included and in no way excludes this folder.

commits:
a49054c
8ebb370

**Comment by danialeresbar** [comment]
The project is Dockerized in order to avoid installing python libraries and packages locally (your machine), even the use of virtual environments should not be necessary. Therefore, although he understands the need not to version these folders, I do not see the case in which we need to create a virtual environment
